name: Release

on:
  release:
    types: [created]

jobs:
  linux-host-publish:
    name: Release on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Release JVM, Android, JS, Linux
        run: ./gradlew bintrayUpload -Ptarget=all_linux_hosted -Pbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}
      - name: Release Metadata
        run: ./gradlew bintrayUpload -Ptarget=meta -Pbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}
  macos-host-publish:
    name: Release on macOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Release iOS, MacOS
        run: ./gradlew bintrayUpload -Ptarget=all_macos_hosted -Pbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}
  linux-host-check:
    name: Check on Ubuntu
    runs-on: ubuntu-latest
    needs: linux-host-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install dependencies
        run: sudo apt-get install nodejs chromium-browser
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Check JVM, Android, JS, Linux
        run: ./gradlew :tools:check-publication:build -Ptarget=all_linux_hosted -Pbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_key=${{ secrets.BINTRAY_KEY }} -Pcheck_publication
  macos-host-check:
    name: Check on macOS
    runs-on: macOS-latest
    needs: [linux-host-publish, macos-host-publish]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check iOS
        run: ./gradlew :tools:check-publication:build -Ptarget=all_macos_hosted -Pbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_key=${{ secrets.BINTRAY_KEY }} -Pcheck_publication
